#!/bin/bash

# 将主目录所有者改成系统创建的用户
permissionFile=${USER_HOME}/.permission.lock
if [ ! -f "${permissionFile}" ]; then
  chown -R "${USERNAME}":"${USERNAME}" "${USER_HOME}"
  su-exec "${USERNAME}" touch "${permissionFile}"
fi

# 复制配置文件到主目录
configFile=${USER_HOME}/application.yml
if [ ! -f "${configFile}" ]; then
  su-exec "${USERNAME}" cp /etc/ddns/application.yml "${configFile}"
fi
