#!/bin/bash

# 将主目录所有者改成系统创建的用户
permissionFile=${USER_HOME}/.permission.lock
if [ "${SET_PERMISSIONS}" = true ] && [ ! -f "${permissionFile}" ]; then
  chown -R "${USERNAME}":"${USERNAME}" "${USER_HOME}"

  if [ ! -f "${permissionFile}" ]; then
    su-exec "${USERNAME}" touch "${permissionFile}"
  fi

  # 复制配置文件到主目录
  su-exec "${USERNAME}" cp /etc/ddns/application.yml "${USER_HOME}"
fi
