#!/bin/bash

[[ -f ./setup ]] && source ./setup

# shellcheck disable=SC2045
# shellcheck disable=SC2006
for conf_file in `ls "${ROOT_DIR}"/application.*`; do
  echo "使用配置文件${conf_file}运行"
  [ -e "${conf_file}" ] && "exec su-exec ${USERNAME} /opt/songjiang --conf ${conf_file}"
  break
done
